// <auto-generated />
namespace Lexicon_LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seed7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed7));
        
        string IMigrationMetadata.Id
        {
            get { return "201704051409014_seed7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
